#ifndef SASHA_UTILS_H
#define SASHA_UTILS_H

enum {ID_CHOOSE_PLAYER_1, ID_CHOOSE_PLAYER_2, ID_GAME_START, ID_MAP, ID_SOUND, ID_GAME_END};
enum {SPECIAL_COLLECTED, SPECIAL_SELF, SPECIAL_OPPONENT};
enum {GAME_VICTORY, GAME_DEFEAT};
#endif // SASHA_UTILS_H
