#ifndef SASHA_UTILS_H
#define SASHA_UTILS_H

enum {ID_CHOOSE_PLAYER_1 = 1, ID_CHOOSE_PLAYER_2, ID_PLAYER_READY, ID_GAME_START, ID_MAP, ID_SOUND, ID_GAME_END};
enum {SPECIAL_COLLECTED = 1, SPECIAL_SELF, SPECIAL_OPPONENT};
enum {GAME_VICTORY = 1, GAME_DEFEAT};
enum {UP = 1, DOWN, LEFT, RIGHT};
enum {SPECIAL_ITEM = 100, FLOOR = 0, OBSTACLE = -1, MONSTER_RED = -5, MONSTER_GREEN = -6, MONSTER_BLUE = -7, PLAYER_ONE = -22, PLAYER_TWO = -23};
#endif // SASHA_UTILS_H
