#ifndef SASHA_UTILS_H
#define SASHA_UTILS_H

enum {ID_CHOOSE_PLAYER_1 = '1', ID_CHOOSE_PLAYER_2 = '2', ID_PLAYER_READY = '3', ID_GAME_START = '4', ID_PLAYER_DIRECTION = '5', ID_REQUEST_MAP = '6', ID_MAP = '7', ID_SOUND = '8', ID_GAME_END = '9'};
enum {SPECIAL_COLLECTED = '1', SPECIAL_SELF = '2', SPECIAL_OPPONENT = '3'};
enum {GAME_VICTORY = '1', GAME_DEFEAT = '2'};
enum {UP = '1', DOWN = '2', LEFT = '3', RIGHT = '4'};
enum {FLOOR = '0', SPECIAL_ITEM = '1', OBSTACLE = '2', MONSTER_RED = '3', MONSTER_GREEN = '4', MONSTER_BLUE = '5', PLAYER_ONE = '6', PLAYER_TWO = '7'};
#endif // SASHA_UTILS_H
